### ISSUE TITLE
missing thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-enrol_paymentexpress#1]
This includes the thirdparty PxPay_Curl.inc.php class - which doesn't include any information about licence etc - you should include the thirdpartylibs.xml file to exclude it from the codechecker scripts and to cover details on the licence etc.

https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

**Comment by euven** [comment]
Thanks @danmarsden -  just added this file with the relevant info ;)
